name: Failure Test Labeled

on:
  pull_request:
    types: [labeled]


jobs:
  generate_integration_tests:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'ci:error')
    name: make it fail
    steps:
      - uses: actions/checkout@v2
      - name: dump github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: fail command
        run: exit 55

  issue-on-error:
    needs: [generate_integration_tests]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    uses: ./.github/workflows/issue_on_error.yml
    with:
      repo: ${{ github.repository }}
      workflow: ${{ github.workflow }}
      run_id: ${{ github.run_id }}
      run_number: ${{ github.run_number }}
      flag_label: ci:bot_issue
      pr_number: ${{ github.event.number }}
      pr_link: ${{ github.event.pull_request._links.html.href }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}